version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=oussama$@
      - DB_NAME=drive
    depends_on:
      - db
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://db:3306/"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oussama$@
      MYSQL_DATABASE: drive
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
